=> merge config from /home/yl3030/COS429_A3/InternImage/classification/configs/without_lr_decay/internimage_t_1k_224.yaml
RANK and WORLD_SIZE in environ: 0/1
O1 O1
[2024-05-03 21:01:51 internimage_t_1k_224](main.py 656): INFO Full config saved to output/internimage_t_1k_224/config.json
[2024-05-03 21:01:51 internimage_t_1k_224](main.py 659): INFO AMP_OPT_LEVEL: O1
AMP_TYPE: float16
AUG:
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  COLOR_JITTER: 0.4
  CUTMIX: 1.0
  CUTMIX_MINMAX: null
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  MIXUP: 0.8
  MIXUP_MODE: batch
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  RANDOM_RESIZED_CROP: false
  RECOUNT: 1
  REMODE: pixel
  REPROB: 0.25
  STD:
  - 0.229
  - 0.224
  - 0.225
BASE:
- ''
DATA:
  BATCH_SIZE: 128
  CACHE_MODE: part
  DATASET: imagenet
  DATA_PATH: ''
  IMG_ON_MEMORY: true
  IMG_SIZE: 224
  INTERPOLATION: bicubic
  NUM_WORKERS: 8
  PIN_MEMORY: true
  ZIP_MODE: false
EVAL_22K_TO_1K: false
EVAL_FREQ: 1
EVAL_MODE: false
LOCAL_RANK: 0
MODEL:
  DROP_PATH_RATE: 0.1
  DROP_PATH_TYPE: linear
  DROP_RATE: 0.0
  INTERN_IMAGE:
    CENTER_FEATURE_SCALE: false
    CHANNELS: 64
    CORE_OP: DCNv3
    DEPTHS:
    - 4
    - 4
    - 18
    - 4
    DW_KERNEL_SIZE: null
    GROUPS:
    - 4
    - 8
    - 16
    - 32
    LAYER_SCALE: null
    LEVEL2_POST_NORM: false
    LEVEL2_POST_NORM_BLOCK_IDS: null
    MLP_RATIO: 4.0
    OFFSET_SCALE: 1.0
    POST_NORM: false
    REMOVE_CENTER: false
    RES_POST_NORM: false
    USE_CLIP_PROJECTOR: false
  LABEL_SMOOTHING: 0.1
  NAME: internimage_t_1k_224
  NUM_CLASSES: 1000
  PRETRAINED: ''
  RESUME: ''
  TYPE: intern_image
OUTPUT: output/internimage_t_1k_224
PRINT_FREQ: 10
SAVE_CKPT_NUM: 1
SAVE_FREQ: 1
SEED: 0
TAG: default
TEST:
  CROP: true
  SEQUENTIAL: false
THROUGHPUT_MODE: false
TRAIN:
  ACCUMULATION_STEPS: 1
  AUTO_RESUME: true
  BASE_LR: 0.000125
  CLIP_GRAD: 5.0
  EMA:
    DECAY: 0.9999
    ENABLE: true
  EPOCHS: 300
  LR_LAYER_DECAY: false
  LR_LAYER_DECAY_RATIO: 0.875
  LR_SCHEDULER:
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    NAME: cosine
  MIN_LR: 1.25e-06
  OPTIMIZER:
    BETAS:
    - 0.9
    - 0.999
    DCN_LR_MUL: null
    EPS: 1.0e-08
    FREEZE_BACKBONE: null
    MOMENTUM: 0.9
    NAME: adamw
    USE_ZERO: false
  RAND_INIT_FT_HEAD: false
  START_EPOCH: 0
  USE_CHECKPOINT: false
  WARMUP_EPOCHS: 20
  WARMUP_LR: 1.25e-07
  WEIGHT_DECAY: 0.05

Traceback (most recent call last):
  File "main.py", line 661, in <module>
    main(config)
  File "main.py", line 170, in main
    data_loader_val, data_loader_test, mixup_fn = build_loader(config)
  File "/home/yl3030/COS429_A3/InternImage/classification/dataset/build.py", line 59, in build_loader
    config=config)
  File "/home/yl3030/COS429_A3/InternImage/classification/dataset/build.py", line 213, in build_dataset
    on_memory=config.DATA.IMG_ON_MEMORY)
  File "/home/yl3030/COS429_A3/InternImage/classification/dataset/cached_image_folder.py", line 313, in __init__
    on_memory=on_memory)
  File "/home/yl3030/COS429_A3/InternImage/classification/dataset/cached_image_folder.py", line 383, in __init__
    with open(osp.join(annotation_root, f'{split}.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'meta_data/train.txt'
/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2394959) of binary: /home/yl3030/anaconda3/envs/internimage/bin/python
Traceback (most recent call last):
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yl3030/anaconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-03_21:01:56
  host      : della-l04g12
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2394959)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
